version: "3.4"  # 3.4 is minimal version that supports extension-fields
volumes:
  database_volume:

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./config.env

x-base:
  &base
  <<: *env_file
  build: .
  volumes:
    - .:/code
  environment:
    - FLASK_ENV=development
    - FLASK_CONFIG=development

services:
  database:
    <<: *env_file
    container_name: database
    volumes:
      - database_volume:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 4306:3306

  backend:
    <<: *base
    container_name: backend
    restart: on-failure
    depends_on:
      - database
    ports:
      - 5000:5000
