class URL:
    ABOUT_GET = "/about"
    CHI_SQUARE_GET = "/chi-square-page"
    CHI_SQUARE_POST = "/chi-square/send-data"
    CHI_SQUARE_GOODNESS_POST = "/chi-square/send-data-goodness"
    CONTACT_GET = "/contact"
    CONTACT_POST = "/contact"
    DONORS_GET = "/donors"
    GENETIC_DISTANCE_GET = "/genetic-distance"
    GENETIC_DISTANCE_POST = "/genetic-distance/send-data-distance"
    HARDY_WEINBERG_GET = "/hardy-weinberg-page"
    HARDY_WEINBERG_POST = "/hardy-weinberg/send-data"
