"""empty message

Revision ID: 11c32ac501ef
Revises: 29dd2460bab1
Create Date: 2018-11-06 12:22:17.602638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c32ac501ef'
down_revision = '29dd2460bab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('profile_pic', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'profile_pic')
    # ### end Alembic commands ###
