"""empty message

Revision ID: 167233c18a24
Revises: 092df91fadf7
Create Date: 2019-08-24 08:27:13.338441

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '167233c18a24'
down_revision = '092df91fadf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ampc_data', 'trained_model', existing_type=mysql.VARCHAR(length=40), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ampc_data', 'trained_model', existing_type=mysql.VARCHAR(length=40), nullable=False)
    # ### end Alembic commands ###
