"""empty message

Revision ID: 1698763d9346
Revises: 46a1b0abaedb
Create Date: 2018-08-03 20:09:01.657993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1698763d9346'
down_revision = '46a1b0abaedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('desc', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'desc')
    # ### end Alembic commands ###
