"""empty message

Revision ID: 1893344efdd5
Revises: 40fc70b51cda
Create Date: 2020-01-07 22:47:15.267096

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1893344efdd5'
down_revision = '40fc70b51cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'article',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=250), nullable=True),
        sa.Column('link', sa.String(length=250), nullable=True),
        sa.Column('pub_date', sa.DateTime(), nullable=True),
        sa.Column('desc', sa.Text(), nullable=True),
        sa.Column('was_published', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feed',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=250), nullable=True),
        sa.Column('url', sa.String(length=250), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    op.drop_table('article')
    # ### end Alembic commands ###
