"""empty message

Revision ID: 22c804e9adf0
Revises: e0aa4241083b
Create Date: 2019-09-05 20:50:16.184553

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '22c804e9adf0'
down_revision = 'e0aa4241083b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apmc_data', sa.Column('model_metrics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apmc_data', 'model_metrics')
    # ### end Alembic commands ###
