"""empty message

Revision ID: 31239f36eaa5
Revises: c6ca4cd82f6a
Create Date: 2019-09-09 20:18:02.670495

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31239f36eaa5'
down_revision = 'c6ca4cd82f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apmc_data', sa.Column('training_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apmc_data', 'training_completed')
    # ### end Alembic commands ###
