"""empty message

Revision ID: 36ddb8e623c7
Revises: fd68830c7c3a
Create Date: 2019-11-07 20:18:59.084549

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36ddb8e623c7'
down_revision = 'fd68830c7c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apmc_data', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column(
        'apmc_data',
        'normalization',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'training_completed',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column('customer_activity', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column(
        'customer_calculations', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=True
    )
    op.drop_constraint('customer_calculations_ibfk_1', 'customer_calculations', type_='foreignkey')
    op.create_foreign_key(None, 'customer_calculations', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.alter_column(
        'customers',
        'is_superuser',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column(
        'pages', 'is_active', existing_type=mysql.TINYINT(display_width=1), type_=sa.Boolean(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pages', 'is_active', existing_type=sa.Boolean(), type_=mysql.TINYINT(display_width=1), existing_nullable=True
    )
    op.alter_column(
        'customers',
        'is_superuser',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.drop_constraint(None, 'customer_calculations', type_='foreignkey')
    op.create_foreign_key('customer_calculations_ibfk_1', 'customer_calculations', 'customers', ['customer_id'], ['id'])
    op.alter_column(
        'customer_calculations', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=False
    )
    op.alter_column('customer_activity', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column(
        'apmc_data',
        'training_completed',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'normalization',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.alter_column('apmc_data', 'customer_id', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # ### end Alembic commands ###
