"""empty message

Revision ID: 40fc70b51cda
Revises: 36ddb8e623c7
Create Date: 2019-12-23 08:38:17.977413

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '40fc70b51cda'
down_revision = '36ddb8e623c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ncbi_mail_packages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('was_sent', sa.Boolean(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ncbi_mails',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('publication_id', sa.String(length=50), nullable=True),
        sa.Column('ncbi_publication_url', sa.String(length=150), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('package_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['package_id'], ['ncbi_mail_packages.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncbi_mails')
    op.drop_table('ncbi_mail_packages')
    # ### end Alembic commands ###
