"""empty message

Revision ID: 420fa573fe03
Revises: bcf8afdaf21e
Create Date: 2018-08-01 21:37:14.296018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '420fa573fe03'
down_revision = 'bcf8afdaf21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('login', table_name='user')
    op.drop_table('user')
    op.drop_table('page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_polish_ci', length=64), nullable=True),
    sa.Column('text', mysql.TEXT(collation='utf8_polish_ci'), nullable=True),
    sa.Column('breadcrumbs', mysql.VARCHAR(collation='utf8_polish_ci', length=220), nullable=True),
    sa.Column('seo_desc', mysql.TEXT(collation='utf8_polish_ci'), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(collation='utf8_polish_ci'), nullable=True),
    sa.Column('seo_tile', mysql.TEXT(collation='utf8_polish_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_polish_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_polish_ci', length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_polish_ci', length=100), nullable=True),
    sa.Column('login', mysql.VARCHAR(collation='utf8_polish_ci', length=80), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_polish_ci', length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8_polish_ci', length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_polish_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('login', 'user', ['login'], unique=True)
    # ### end Alembic commands ###
