"""empty message

Revision ID: 452212c1cce1
Revises: 82dc2b22b8f3
Create Date: 2019-07-21 16:02:51.907584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452212c1cce1'
down_revision = '82dc2b22b8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_superuser')
    # ### end Alembic commands ###
