"""empty message

Revision ID: 78e418962507
Revises: 94f874c42df8
Create Date: 2019-08-31 10:25:38.384249

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78e418962507'
down_revision = '94f874c42df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'model_data',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('ampcdata_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('X_train', sa.BLOB(), nullable=True),
        sa.Column('X_test', sa.BLOB(), nullable=True),
        sa.Column('y_train', sa.BLOB(), nullable=True),
        sa.Column('y_test', sa.BLOB(), nullable=True),
        sa.ForeignKeyConstraint(['ampcdata_id'], ['ampc_data.id'], name='model_data_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='latin1',
        mysql_engine='InnoDB',
    )
    # ### end Alembic commands ###
