"""empty message

Revision ID: 806e717d120c
Revises: 11c32ac501ef
Create Date: 2018-11-13 15:13:27.169514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806e717d120c'
down_revision = '11c32ac501ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_calculations', sa.Column('title', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_calculations', 'title')
    # ### end Alembic commands ###
