"""empty message

Revision ID: 87745977992f
Revises: 
Create Date: 2019-07-09 09:06:41.687701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87745977992f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=120), nullable=True),
    sa.Column('user_data', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    # ### end Alembic commands ###
