"""empty message

Revision ID: 94f874c42df8
Revises: 167233c18a24
Create Date: 2019-08-30 17:18:00.740693

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '94f874c42df8'
down_revision = '167233c18a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'model_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ampcdata_id', sa.Integer(), nullable=False),
        sa.Column('X_train', sa.LargeBinary(), nullable=True),
        sa.Column('X_test', sa.LargeBinary(), nullable=True),
        sa.Column('y_train', sa.LargeBinary(), nullable=True),
        sa.Column('y_test', sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(['ampcdata_id'], ['ampc_data.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_data')
    # ### end Alembic commands ###
