"""empty message

Revision ID: a28c798f4172
Revises: 9172fcbd37dd
Create Date: 2018-08-01 11:31:46.486674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28c798f4172'
down_revision = '9172fcbd37dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('breadcrumbs', sa.String(length=220), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'breadcrumbs')
    # ### end Alembic commands ###
