"""empty message

Revision ID: b33b0ba7eb86
Revises: 1698763d9346
Create Date: 2018-08-04 21:27:44.322345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b33b0ba7eb86'
down_revision = '1698763d9346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('seo_title', sa.String(length=85), nullable=True))
    op.drop_column('pages', 'seo_tile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('seo_tile', mysql.VARCHAR(collation='utf8_polish_ci', length=85), nullable=True))
    op.drop_column('pages', 'seo_title')
    # ### end Alembic commands ###
