"""empty message

Revision ID: c6ca4cd82f6a
Revises: 22c804e9adf0
Create Date: 2019-09-08 20:47:32.462573

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c6ca4cd82f6a'
down_revision = '22c804e9adf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apmc_data', sa.Column('report', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apmc_data', 'report')
    # ### end Alembic commands ###
