"""empty message

Revision ID: e8d1ca60c45f
Revises: a28c798f4172
Create Date: 2018-08-01 20:56:00.756282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d1ca60c45f'
down_revision = 'a28c798f4172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('breadcrumbs', sa.String(length=220), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'breadcrumbs')
    # ### end Alembic commands ###
