"""empty message

Revision ID: fd68830c7c3a
Revises: 31239f36eaa5
Create Date: 2019-09-10 18:50:00.228126

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd68830c7c3a'
down_revision = '31239f36eaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'apmc_data',
        'dataset',
        existing_type=mysql.VARCHAR(length=40),
        type_=sa.String(length=80),
        existing_nullable=False,
    )
    op.alter_column(
        'apmc_data',
        'normalization',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'report',
        existing_type=mysql.VARCHAR(length=40),
        type_=sa.String(length=80),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'training_completed',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column(
        'customers',
        'is_superuser',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.alter_column(
        'pages', 'is_active', existing_type=mysql.TINYINT(display_width=1), type_=sa.Boolean(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pages', 'is_active', existing_type=sa.Boolean(), type_=mysql.TINYINT(display_width=1), existing_nullable=True
    )
    op.alter_column(
        'customers',
        'is_superuser',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'training_completed',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'report',
        existing_type=sa.String(length=80),
        type_=mysql.VARCHAR(length=40),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'normalization',
        existing_type=sa.Boolean(),
        type_=mysql.TINYINT(display_width=1),
        existing_nullable=True,
    )
    op.alter_column(
        'apmc_data',
        'dataset',
        existing_type=sa.String(length=80),
        type_=mysql.VARCHAR(length=40),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
