"""
Constants.py
"""

CHI_SQUARE = "chi_square"
CHI_SQUARE_GOODNESS = "chi_square_goodness"
GENETIC_DISTANCE = "genetic_distance"
HARDY_WEINBERG = "hardy_weinberg"
PIC_DOMINANT = "pic_dominant"
PIC_CODOMINANT = "pic_codominant"
DOT_PLOT_RAW_SEQ = "dot_plot_raw_seq"
DOT_PLOT_GENEBANK_IDS = "dot_plot_genebank_ids"
CONSENSUS_SEQUENCE_RAW_SEQ = "consensus_sequence_raw_seq"
CONSENSUS_SEQUENCE_FILE_SEQ = "consensus_sequence_file_seq"
CONSENSUS_SEQUENCE_GENE_BANK = "onsensus_sequence_gene_bank"
SEQUENCES_TOOLS = "sequences_tools"
